name: Debugging purpose archive me when done

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
        - staging
        - main


jobs:
  debug-workflow:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
            DEBUG_SECRET: ${{ secrets.DEBUG_SECRET }}
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  
      - name: display secrets
        run: |
            echo "this should be hidden no? repo scret "
            echo "repo level secret: ${{secrets.DEBUG_SECRET}}"
            echo "env secret: ${{secrets.DEBUG_ENV_SECRET}}"
            echo "raw dog repo secret $DEBUG_SECRET"
            echo "raw dog env secret $DEBUG_ENV_SECRET"
            echo "for real hide me ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  "

      - name: Use DEBUG_ENV_SECRET as an env var 
        env:
            DEBUG_ENV_SECRET: ${{ secrets.DEBUG_ENV_SECRET }}        
        run: |
            echo "raw dogged DEBUG_ENV_SECRET"
            echo $DEBUG_ENV_SECRET

      - name: Use DEBUG_SECRET an env var raw dogged  
        run: |
            echo $DEBUG_SECRET
            echo "google env level set secret secret"
            echo $GOOGLE_APPLICATION_CREDENTIALS

            