# This was initially setup to automatically merge changes from staging back into main. Giving up for now due to syncing issues
name: Merge Staging to Main

on:
  workflow_run:
    workflows: ["Staging - Python Backend Tests"]
    types:
      - completed

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message for specific tags
        run: |
          if grep -qiE "\[skip-all\]|\[wip\]|\[skip ci\]" <<< "$(git log --format=%B -n 1 ${{ github.sha }})"; then
            echo "Skipping tests as commit message contains, [skip-all], [wip], or [skip ci]."
            exit 78  # Exit with a neutral code
          else
            echo "Commit message does not contain any skip tags. Proceeding with auto merge."
          fi


  merge_to_main:
    runs-on: ubuntu-latest

    needs: check-commit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "Github Actions"

      - name: Merge staging into main
        run: |
          git checkout main
          git merge staging --no-ff --no-edit
          git push origin main
        env:
          GH_TOKEN: ${{secrets.ACTION_PAT}}


