name: Merge Staging to Main

on:
 push:
  branches:
    - cicd_testing
 pull_request:
  branches:
    - cicd_testing

jobs:
 merge_to_main:
 runs-on: ubuntu-latest

 steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set Git config
     run: |
       git config --local user.email "actions@users.noreply.github.com"
       git config --local user.name "Github Actions"   

   - name: Fetch latest changes on main and staging branches
     run: |
       git fetch origin main:main
       git fetch origin cicd_testing:cicd_testing

   - name: Merge cicd_testing into main
     run: |
       git checkout main
       git merge --no-ff --allow-unrelated-histories cicd_testing -m "Automation: merge cicd_testing to main"

   - name: Push changes to main
     run: |
       git push origin main
