name: DEEBUGGING DELETE ME ON COMPLETE Merge Staging to Main

on:
  push:
    branches:
      - cicd_testing
  pull_request:
    branches:
      - cicd_testing

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "Github Actions"      

      - name: Merge to Staging to Main
        run: |
          git fetch origin staging:staging
          git checkout main
          git pull
          git merge --no-ff staging -m "Automation-PAT-bot: merge staging to main"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.ACTION_PAT}}

          

