name: Deployments

concurrency: production

on:
  workflow_run:
    workflows: ["Executes Tests"]
    branches: [main]
    types:
      - completed

# TODO for this https://github.com/marketplace/actions/cloud-functions-deploy
# build full ci cd pipeline in the future

# TODO have a build step too, currently autodeploy cloud funcs

jobs:
    deploy-firebase-functions:
        # run only valid run
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        # needs: run-firebase_functions-suite
        runs-on: ubuntu-latest        
        
