name: Staging - Firebase Cloud Functions Run Unit Test Suite # Tag: [firebase_functions]

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  check-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message for specific tags
        run: |
          if grep -qiE "\[client_react\]|\[app_flask\]|\[skip-all\]|\[wip\]|\[skip ci\]" <<< "$(git log --format=%B -n 1 ${{ github.sha }})"; then
            echo "Skipping tests as commit message contains, [client_react], [app_flask], [skip-all], [wip], or [skip ci]."
            exit 78  # Exit with a neutral code
          else
            echo "Commit message does not contain any skip tags. Proceeding with tests."
          fi

  run-test-suite:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: database/firebase/functions
    
    needs: check-commit
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Run test on the functions/tests directory

      - name: Check test status and prevent merge/push on failure
        if: ${{ failure() }}
        run: exit 1  # Exit with a non-zero code to fail the workflow