name: Merge Staging to Main

on:
  workflow_run:
    workflows: ["Staging - Python Backend Tests"]
    types:
      - completed

jobs:
  check-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message for tags
        run: |
          if grep -qiE "\[skip-all\]|\[skip ci\]" <<< "$(git log --format=%B -n 1 ${{ github.sha }})"; then
            echo "Skipping pipeline as commit message contains [skip-all], or [skip ci]."
            exit 78  # Exit with a neutral code
          else
            echo "Commit message does not contain any skip tags. Proceeding."
          fi

  merge_to_main:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"      

      - name: Merge to Main
        run: |
          git fetch origin staging:staging
          git checkout main
          git pull
          git merge --no-ff main -m "Automation: merge staging to main"
          git push origin main

