name: Merge Staging to Main

on:
  workflow_run:
    workflows: ["Staging - Python Backend Tests"]
    types:
      - completed

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge to Main
        run: |
          git checkout main
          git merge staging  # Merge staging into main
          git push origin main
